### ISSUE TITLE
Fix phpfmt save auto formating issue

### ISSUE THREAD

**Issue by axelra82** [chas-academy/u05-imdb-clone-team4#11]
While working on a PHP file I noticed that our PHP formatting plugin ([phpfmt](https://marketplace.visualstudio.com/items?itemName=kokororin.vscode-phpfmt)) for VS removes `use` statements when saving php files (with format on save).

I found a temporary fix for this [here](https://github.com/kokororin/vscode-phpfmt/issues/68). Seeing as the repo hasn't been updated in over 2 years and is now archived, it's safe to assume this issue will not be addressed by the author.

**NOTE!** Leave issue open until everyone has made a comment here. We need to make sure everyone has read this and fixed it on their end (so we don't get a bunch of code missing use statements 😂)

**Comment by Tuliany** [comment]
Den inställning ska nu finnas med i seetingsfilen i VScode mappen på Main-branch. Det är bara att "git pull" från main. 
När alla har "pullat" från main och checkat av i issuen, kan vi radera denna tråd. 
@SkySails @stenwall @VeronicaT78 @johannasjo @Braggedtooth @axelra82
