### ISSUE TITLE
Scaffold IMDB app using sitemap as reference

### ISSUE THREAD

**Issue by SkySails** [chas-academy/u05-imdb-clone-team4#8]
The current sitemap allows us to start working on the base scaffolding of our app. This involves creating the routes needed and, to some extent, creating markup for shared/commonly occurring elements like footers, headers etc.

The sitemap is available [here](https://lucid.app/lucidchart/a7dd714a-9779-4e92-98b8-90606e9d13e6/edit?s=772&name=docs&callback=close&v=1141&callback_type=back&page=0_0#?folder_id=home&browser=icon)

**Comment by johannasjo** [comment]
Kommande sprint:

- loopar för korten
- header
- footer
- Footer-rubriker får egna views 
- ev. Grid-skelett för main page
