### ISSUE TITLE
Investigate user authentication options

### ISSUE THREAD

**Issue by SkySails** [chas-academy/u05-imdb-clone-team4#9]
## Introduction

While scaffolding is important, user authentication is going to be a vital and possibly blocking part as soon as the scaffolding is done. To be effective, we should be prepared by having the authentication system figured out beforehand.

A good first step is to decide what implementation we are going to use. Should we use something provided by Laravel, or perhaps use the already implemented system provided by Backpack? Maybe there are other, better options?

This issue purely addresses the investigation phase. The investigation may be a group effort, but it can also be carried out by an individual.

When the investigation is done, or when the investigating party decides that it is done, the results may be presented to the rest of the group. The goal is to make a proposal for a system/solution that the group is comfortable with.

Please think about the following during the investigation:
  - What options are there?
  - What are the main pros/cons of each option?
  - How well does each option meet our requirements?
  - How big an effort would implementing each option be?

## Requirements

To determine the requirements, please look at the [sitemap](https://lucid.app/lucidchart/a7dd714a-9779-4e92-98b8-90606e9d13e6/edit?s=772&name=docs&callback=close&v=1141&callback_type=back&page=0_0#?folder_id=home&browser=icon) as well as the [backlog](https://github.com/chas-academy/u05-imdb-clone-team4/projects/1).

Ideally, we want an implementation is able to perform the following at the very least:
 - Sign users in and out
 - Define and keep track of a scope for each user
 - Add user info (name, profile picture etc)
 - Integrate with Backpack

**Comment by axelra82** [comment]
I'll try and set some time aside for this durring the coming weekend. My initial response (without further due diligence) is that we should use one of the existing options, i.e. Laravel or Backpack (_leaning strongly towards Backpack_).

Although there are obviously other third party options out there, e.g. [Auth0](https://auth0.com), i believe that the easiest route here will be to use Backpack since we'll be using it for admins as well (seeing as it is so tightly integrated with Backpack) 🤓

**Comment by SkySails** [comment]
[This](https://laravel.com/docs/8.x/authentication#summary-choosing-your-stack) might be worth taking into consideration as well. There is a slight possibility that relying solely on Backpack for authentication is going to create more overhead for us during the integration with Laravel itself than if we'd just go with Laravel all the way. Again, this is the reason why we have an investigation first, in order to make sure we choose a feasible path before committing.

**Comment by axelra82** [comment]
As per @SkySails we'll be looking in to either native Laravel user management or official backpack add-on [PermissionManager](https://github.com/Laravel-Backpack/PermissionManager)

**Comment by axelra82** [comment]
See PR #13 for current status and progress.
